{% set version = "1.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pillar
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pillar_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pillar/pillar_{{ version }}.tar.gz
  sha256: dd6d56b73bdbb7908d6c65371c835599a9417b25129b499c486c9f6320e719b1

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-cli >=1.0.0
    - r-crayon >=1.3.4
    - r-fansi >=0.4.0
    - r-rlang >=0.3.0.1
    - r-utf8 >=1.1.3
  run:
    - r-base
    - r-cli >=1.0.0
    - r-crayon >=1.3.4
    - r-fansi >=0.4.0
    - r-rlang >=0.3.0.1
    - r-utf8 >=1.1.3

test:
  commands:
    - $R -e "library('pillar')"           # [not win]
    - "\"%R%\" -e \"library('pillar')\""  # [win]

about:
  home: https://github.com/r-lib/pillar
  license: GPL-3
  summary: Provides a 'pillar' generic designed for formatting columns of data using the full
    range of colours provided by modern terminals.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: pillar
# Title: Coloured Formatting for Columns
# Version: 1.3.1
# Authors@R: c( person("Kirill", "Muller", , "krlmlr+r@mailbox.org", role = c("aut", "cre")), person("Hadley", "Wickham", role = "aut"), person("RStudio", role = "cph") )
# Description: Provides a 'pillar' generic designed for formatting columns of data using the full range of colours provided by modern terminals.
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# URL: https://github.com/r-lib/pillar
# BugReports: https://github.com/r-lib/pillar/issues
# Imports: cli (>= 1.0.0), crayon (>= 1.3.4), fansi (>= 0.4.0), methods, rlang (>= 0.3.0.1), utf8 (>= 1.1.3)
# Suggests: knitr (>= 1.19), lubridate (>= 1.7.4), testthat (>= 2.0.0), withr (>= 2.1.2)
# RoxygenNote: 6.1.1
# Collate: 'capital.R' 'compat-purrr.R' 'dim.R' 'extent.R' 'multi.R' 'ornament.R' 'pillar-package.R' 'pillar.R' 'rowid-capital.R' 'rowid-data.R' 'rowid-title.R' 'rowid-type.R' 'scientific.R' 'shaft.R' 'shaft-simple.R' 'sigfig.R' 'spark-bar.R' 'spark-line.R' 'strrep.R' 'styles.R' 'testthat.R' 'tick.R' 'title.R' 'type-sum.R' 'type.R' 'utils.R' 'width.R' 'zzz.R'
# NeedsCompilation: no
# Packaged: 2018-12-15 16:32:35 UTC; kirill
# Author: Kirill Muller [aut, cre], Hadley Wickham [aut], RStudio [cph]
# Maintainer: Kirill Muller <krlmlr+r@mailbox.org>
# Repository: CRAN
# Date/Publication: 2018-12-15 17:00:03 UTC
