{% set version = '1.2.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pillar
  version: {{ version|replace("-", "_") }}

source:
  fn: pillar_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/pillar_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pillar/pillar_{{ version }}.tar.gz
  sha256: 676d6e64754ce42c2789ca3521eeb576c873afc3b09adfdf2c97f03cbcddb8ce

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-cli >=1.0.0
    - r-crayon >=1.3.4
    - r-rlang >=0.2.0
    - r-utf8 >=1.1.3
  run:
    - r-base
    - r-cli >=1.0.0
    - r-crayon >=1.3.4
    - r-rlang >=0.2.0
    - r-utf8 >=1.1.3

test:
  commands:
    - $R -e "library('pillar')"           # [not win]
    - "\"%R%\" -e \"library('pillar')\""  # [win]

about:
  home: https://github.com/r-lib/pillar
  license: GPL-3
  summary: Provides a 'pillar' generic designed for formatting columns of data using the full
    range of colours provided by modern terminals.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - ocefpaf
