{% set version = "1.2.1" %}

package:
  name: r-pillar
  version: {{ version }}

source:
  fn: pillar_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/pillar_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/pillar/pillar_{{ version }}.tar.gz
  sha256: 6de997a43416f436039f2b8b47c46ea08d2508f8ad341e0e1fd878704a3dcde7

build:
  number: 0
  script: R CMD INSTALL --build .
  skip: True  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-cli
    - r-crayon >=1.3.4
    - r-rlang
    - r-utf8 >=1.1.3
  run:
    - r-base
    - r-cli
    - r-crayon >=1.3.4
    - r-rlang
    - r-utf8 >=1.1.3

test:
  commands:
    - $R -e "library('pillar')"  # [not win]
    - "\"%R%\" -e \"library('pillar')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/pillar
  license: GPL-3
  summary: Provides a 'pillar' generic designed for formatting columns of data using the full
    range of colours provided by modern terminals.

extra:
  recipe-maintainers:
    - ocefpaf
