{% set version = '1.3.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pillar
  version: {{ version|replace("-", "_") }}

source:
  fn: pillar_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/pillar_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pillar/pillar_{{ version }}.tar.gz
  sha256: aed845ae4888be9a7340eed57536e3fe6cb46e89d905897fb9b0635797cfcae0

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-cli >=1.0.0
    - r-crayon >=1.3.4
    - r-fansi
    - r-rlang >=0.2.0
    - r-utf8 >=1.1.3
  run:
    - r-base
    - r-cli >=1.0.0
    - r-crayon >=1.3.4
    - r-fansi
    - r-rlang >=0.2.0
    - r-utf8 >=1.1.3

test:
  commands:
    - $R -e "library('pillar')"           # [not win]
    - "\"%R%\" -e \"library('pillar')\""  # [win]

about:
  home: https://github.com/r-lib/pillar
  license: GPL-3
  summary: Provides a 'pillar' generic designed for formatting columns of data using the full
    range of colours provided by modern terminals.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - ocefpaf
