appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: nks0S0tTR74NzHiDZu5fio7N9n+EijYwCU3e4j627rwSAiZNoOEvSLOjHB0uKh/OmAcgUEDL6yaOdhuSEkz4saxSo6c7jkluu4dJdNlD+eWUF1S7vRo1eoaN/i9XRXmhQrgvwQrlTAV/HfRFewAclffLE0vcY3baEJk1LpdAatVePZrN0XRBTySAUjGKfRBifcVRRZFtyeLXrKWq087/QMYpHceFkfDML6RIBbz3uz8u7vhAh7MKE5Jp7GkTLouai2uZJ26WXbYrafBIdaXv/4CpNIdCgiSX/e1j+TjqCFMDbe/vMEdihkvRhSSec/I07ZdEyfXEgyuHLRE2WqBtKaykHO3rpijWd4/6xwhXzFMRV5C60vkNX4WU7b+xnB0POhH6nlkc+HIhYqv0ersvripJGLQ07D8Ef0MamQ1sdGNx/pOYDVVyic4Hxb6AZygb5bJYN8UIqNjApyzkPVotA/NOEk81b+diP/BZBOYbMmmPcFDnVZ89RxKkWJxDbDAPeYMVoxuZWYnBrGdA9gZFCHgTMfZUifW6zStTrS7QfPbfa0YlquWyosdhQPPmwIGDqZec5a8HnQgsDgLLODBK6dOxzhU4Y7DNPXH5bsLXhZOcGGdf8i3DzMzXDU6PI/HnV9YsNkXBuCDqUk+U7rzv8nMufoSeSw647TRbcS3UGdU=
