travis:
  secure:
    BINSTAR_TOKEN: 42S8udXDKmmwtXbYU6dgEGO1OQAG9FQKCd9OkExeF9cLrjH2apta0sCAAhHUaUWoR0wJBSBA5hDLtOEIn1Q0gglI0nMFtr1arbfmhzwRv3mZiZZCFXqoL4OVxSGOkhpDHv4nsmGVkBxtjYOhT+apnKgxLkIdjXJictLhWPA3GNahCPa8G7AqWAv6wtwmz1O36R7jeYJvM0rYpvIM04i3/bDXEbPXxiYluicDyLkRKJ7ZcgycLixrphfSecSQDUIC8Lrx3ajOYYQRTch/4lzXd5BHQQTzv7Z/jTpb5FIPB+36yJSTxosAfFlh4+UQ6a+TroC+o78CzSs3f+FJShoL1eDVhAVrESKcR4VU5vBGmgmOKEom8ZVa1oek6eHMth32iCZ7Qcd8bT9sPOacOjOZfYWWscMo7N1XeS+isoDS8MULA6XVgCpa/f9sZNIpoyrbYu8bYSgLjGHGwpEemt8m3UZoLKQtDzoU+/v4TOgZfpbvlv78JZKUic1s8DsRo2aDdDVxuBp2n99xs/o2DFgd7H7/bvtvUhdfgtQcZEw/XIhCFks2L4u9JAlyVbeP2I613LBo7y7hXVKv4cs+uYJ1+ot84GD1KXUgJkrNsO2Wn71oZhq1vJP4UDJmUOF6lQpEIluD3GOKQP+S2BMCFtBmVlI85tVHnwHEFrJyhVXppAs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
